name: Build Vite App (Bun)

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
        contents: write
        
    steps:
      - uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install deps
        run: bun install --frozen-lockfile

      - name: Build with Vite
        run: bun run build

      - name: Commit dist folder
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git fetch origin
          git checkout -B build-artifacts
          git add -f dist
          git commit -m "Build artifacts"
          git push origin build-artifacts --force
